"""notification_refinements

Revision ID: a81237dc35d2
Revises: cf25a9a7a543
Create Date: 2026-06-09 23:12:47.210754

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a81237dc35d2'
down_revision: str | None = 'cf25a9a7a543'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('error_message', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('read_at', sa.DateTime(), nullable=True))
    op.add_column(
        'notifications',
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()'))
    )
    op.alter_column('notifications', 'scheduled_for',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'])
    op.create_index('ix_notifications_status', 'notifications', ['status'])
    op.create_index('ix_notifications_scheduled_for', 'notifications', ['scheduled_for'])
    op.create_index('ix_notifications_schedule_id', 'notifications', ['schedule_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_schedule_id', table_name='notifications')
    op.drop_index('ix_notifications_scheduled_for', table_name='notifications')
    op.drop_index('ix_notifications_status', table_name='notifications')
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.alter_column('notifications', 'scheduled_for',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('notifications', 'updated_at')
    op.drop_column('notifications', 'read_at')
    op.drop_column('notifications', 'error_message')
    # ### end Alembic commands ###
